### PR TITLE
Try to replace setup.py with Pyproject

### PR DESCRIPTION
**Pull request by olliethomas**
Not sure that this will work first time

### CODE REVIEW

**Comment by olliethomas** [comment]
@thomkeh do you have a preference about this one way or the other? At the moment when I use ethicml directly from github as a dependency in poetry, for some reason it doesn't get all the dependencies that ethicml needs, which is a faff. I'm hoping that by ethicml being managed by poetry too will make this problem go away

**Comment by thomkeh** [comment]
@olliethomas sorry that I didn't respond! I prefer poetry!

**Comment by thomkeh** [comment]
This will have conflicts with #433 :/

**Comment by olliethomas** [comment]
let's get #433 in, we can deal with conflicts then

**Comment by thomkeh** [comment]
@olliethomas rebased and conflicts solved

**Pull request merged**
