### PR TITLE
Use mypy to check the code

### PR DESCRIPTION
**Pull request by thomkeh**
* add mypy.ini
* add run_mypy.py
* add check_all.py
* run run_mypy.py on Azure

### CODE REVIEW

**Comment by olliethomas** [comment]
Does mypy cause the build to fail if it finds something?

**Comment by thomkeh** [comment]
> Does mypy cause the build to fail if it finds something?

Yes, for the moment. We can wrap it in a script like you did with pylint to not fail on every error.

**Comment by olliethomas** [comment]
That might be nice, though at first glance mypy doesn't return a score, which made the pylint script trivial.

**Comment by thomkeh** [comment]
Tests pass now

**Comment by olliethomas** [comment]
I guess we’ve already done the test to demonstrate the build fails if mypy flags anything

**Comment by thomkeh** [comment]
> I guess we’ve already done the test to demonstrate the build fails if mypy flags anything

Yes, the first time it failed because mypy found an error.

**Comment by thomkeh** [comment]
I didn't remove `python -m pytest tests/` from `azure_pipelines.yml` in this PR.

**Pull request merged**
