### PR TITLE
Synthetic1

### PR DESCRIPTION
**Pull request by olliethomas**

### CODE REVIEW

**Comment by thomkeh** [comment]
```
ethicml/data/csvs/make_synthetic_1.py:8: error: Function is missing a type annotation  [no-untyped-def]
ethicml/data/csvs/make_synthetic_1.py:13: error: Function is missing a return type annotation  [no-untyped-def]
```
naughty!

**Comment by olliethomas** [comment]
This *should* pass once DST is updated

**Comment by olliethomas** [comment]
can I merge this @thomkeh or will it be easier for me to rebase onto your latest pr?

**Comment by thomkeh** [comment]
go ahead!

**Pull request merged**
