### PR TITLE
Add Zafar algorithm

### PR DESCRIPTION
**Pull request by thomkeh**

### CODE REVIEW

**Comment by thomkeh** [comment]
@olliethomas do we want to add a test for this? I'm afraid it will be slow.

**Comment by olliethomas** [comment]
sure, I'll do one now

**Comment by thomkeh** [comment]
It would be a bit more efficient if only download the code once for the 3 Zafar algorithms and remove it once. Like I did with fair GPyTorch:

```python
@pytest.fixture(scope="module")
def gpyt_models():
    # the gpyt models are created together because they share a git repository
    gpyt = GPyT(epochs=2, length_scale=2.4)
    gpyt_dem_par = GPyTDemPar(epochs=2, length_scale=0.05)
     gpyt_eq_odds = GPyTEqOdds(epochs=2, tpr=1.0, length_scale=0.05)
    yield (gpyt, gpyt_dem_par, gpyt_eq_odds)
    gpyt.remove()  # only has to be called from one of the models because they share a directory
```

The problem is maybe that this not an entirely realistic test.

**Comment by olliethomas** [comment]
always run the check_all script before pushing, Oliver......

**Comment by olliethomas** [comment]
I agree, I know it will make the test run a bit faster.... Maybe we should have it for the tests. But, In day to day use, downloading all three separately is far more realistic.

One thing that I wasn't sure on is how to go about running the cross validator on the zafar model (in a pretty way)

**Comment by thomkeh** [comment]
> One thing that I wasn't sure on is how to go about running the cross validator on the zafar model (in a pretty way)

What's the problem with

**Comment by olliethomas** [comment]
I think I have an idea

**Comment by thomkeh** [comment]
Can this be merged, @olliethomas ? Or do you want to change the tests in some way?

**Comment by olliethomas** [comment]
I'm fine with it

**Pull request merged**
